[target.aarch64-apple-darwin]
linker = "aarch64-apple-darwin25-clang"
ar = "aarch64-apple-darwin25-ar"

[target.x86_64-apple-darwin]
linker = "x86_64-apple-darwin25-clang"
ar = "x86_64-apple-darwin25-ar"

