/*
 * This source file was generated by the Gradle 'init' task
 */
package com.team2813.gradle;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * A simple unit test for the 'com.team2813.gradle.git_version' plugin.
 */
class GitVersionPluginTest {
    @Test
    void pluginRegistersPropertyGenerationTask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        var container = project.getPlugins();
        container.apply("java");
        container.apply("com.team2813.gradle.git_details");

        // Verify the result
        assertNotNull(project.getTasks().findByName(GitVersionPlugin.GEN_PROPERTY_TASK_NAME));
    }
}
