/*
 * This source file was generated by the Gradle 'init' task
 */
package com.team2813.gradle;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * A simple unit test for the 'com.team2813.git_version.greeting' plugin.
 */
class GitVersionPluginTest {
    @Test void pluginRegistersATask() {
        // Create a test project and apply the plugin
//        Project project = ProjectBuilder.builder().build();
//        project.getPlugins().apply("com.team2813.git_version.greeting");

        // Verify the result
//        assertNotNull(project.getTasks().findByName("greeting"));
    }
}
