/*
 * This source file was generated by the Gradle 'init' task
 */
package com.team2813.gradle;

import org.gradle.api.DefaultTask;
import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.gradle.api.plugins.JavaPlugin;
import org.gradle.api.plugins.JavaPluginExtension;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.Input;
import org.gradle.api.tasks.SourceSet;
import org.gradle.api.tasks.TaskAction;

public class GitVersionPlugin implements Plugin<Project> {
    private static final String EXTENSION_NAME = "git_version";
    private static final String BINARY_NAME = "git_version";
    private static final String GEN_DIR = "generated/sources/" + EXTENSION_NAME;
    private static final String PROPERTY_PACKAGE = "properties";
    private static final String DEFAULT_PROPERTIES_FILE = "git-info.properties";
    private static final String GEN_PROPERTY_TASK_NAME = "createGitProperties";

    interface GitVersionExtension {
        Property<String> getGitPropertyPackage();
        Property<String> getPropertyFileName();
    }

    static {
        System.loadLibrary(BINARY_NAME);
    }

    /**
     * Generate a Java properties file with git information.
     *
     * @param repoPath The path to the git repository
     * @param propertyPath The path to the Java properties file
     * @return an error code
     */
    private static native int generateGitProperties(String repoPath, String propertyPath);

    @Override
    public void apply(Project project) {
        // allow configuration w/defaults
        var extension = project.getExtensions().create(EXTENSION_NAME, GitVersionExtension.class);
        extension.getGitPropertyPackage().convention(PROPERTY_PACKAGE);
        extension.getPropertyFileName().convention(DEFAULT_PROPERTIES_FILE);

        // create task to generate properties file
        var taskProvider = project.getTasks().register(GEN_PROPERTY_TASK_NAME, GenerateSources.class);
        taskProvider.configure(task -> {
            task.getGitPropertyPackage().set(extension.getGitPropertyPackage());
            task.getPropertyFileName().set(extension.getPropertyFileName());
        });
        // which should be depended on by the java compilation task
        project.getTasks().getByName(JavaPlugin.COMPILE_JAVA_TASK_NAME).dependsOn(taskProvider);

        // add generated source set to the main source set.
        var sourceSets = project.getExtensions().getByType(JavaPluginExtension.class).getSourceSets();
        var generatedSourceSets = project.getLayout().getBuildDirectory().dir(GEN_DIR);
        sourceSets.getByName(SourceSet.MAIN_SOURCE_SET_NAME).getJava().srcDir(generatedSourceSets);
    }

    static abstract class GenerateSources extends DefaultTask {
        public GenerateSources() {}

        @Input
        abstract Property<String> getGitPropertyPackage();
        @Input
        abstract Property<String> getPropertyFileName();

        @TaskAction
        void createGitProperties() {
            Project project = getProject();
            String repoPath = project.getPath();
            String gitPropertyPackage = getGitPropertyPackage().get();
            String propertyFileName = getPropertyFileName().get();
            String relPropertyPath = GEN_DIR + "/" + gitPropertyPackage.replace('.', '/') + "/resources/" + propertyFileName;

            String propertyPath = project.absoluteProjectPath(relPropertyPath);
            int error = generateGitProperties(repoPath, propertyPath);
            if (error != 0) {
                switch (error) {
                    case 0b0001_0001:
                        throw new IllegalArgumentException("JNI code failed to get repository path");
                    case 0b0001_0010:
                        throw new RuntimeException("JNI code failed to get property file path");
                    case 0b0010_0001:
                        throw new RuntimeException("A fundamental assumption of git state was broken!");
                    case 0b0010_0010:
                        throw new RuntimeException("Failed to write properties file! See stderr for more info!");
                    default:
                        throw new AssertionError("Unknown error code was thrown!");
                }
            }
        }
    }
}
